
baseurl: /TheEndlessFrontier

collections:
  episodes:
    output: true

defaults:
  - scope:
      path: ""
      type: "episodes"
    values:
      layout: "episode"
  - scope:
      path: ""
    values:
      layout: "default"